### ISSUE TITLE
macOS : generated PostInstall script needs full path to reference GurobiLink.dylib

### ISSUE THREAD

**Issue by achaseturner** [WolframResearch/GurobiLink#1]
# ISSUE

While installing a Debug version of GurobiLink, the generated PostInstall SHELL script fails with an unresolved filename error when `install_name_tool` references the file name `Gurobilink.dylib`.

# TEMPORARY WORKAROUND

Two workarounds are possible:
* replace the first `cd ~/src/git/Paclets/GurobiLink` with `cd ~/src/git/Paclets/GurobiLink/$CONFIGURATION`
* Manually update the PostInstall SHELL script replacing `Gurobilink.dylib` with the fully qualified path name `~/src/git/Paclets/GurobiLink/Debug/GurobiLink.dylib`

# ENVIRONMENT
macOS: 12.0
xCode : 12.5.1
CMake : 3.21.2 ( ~/Applications/CMake.app )
Mathematica: 12.3 ( ~/Applications/Mathematica.app )
GurobiLink : ~/src/git/Paclets/GurobiLink

# How the PostInstall ShellScript was created

`cmake -DWOLFRAM_INSTALLATION=~/Applications/Mathematica.app/Contents -DGUROBI_VERSION=9.1.2 -DGUROBI_HOME=/Library/gurobi912/macos_universal2 ..`

`cmake --build . --config Debug --target install`

**Comment by ilian8** [comment]
Thank you for the report; should be fixed in the current sources.

**Comment by achaseturner** [comment]
Thanks for creating GurobiLink, and the quick turnaround here!
